/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
//Write "Hello World" to I2C LCD Display
#include <stdint.h>
#include <stdio.h>
#include "gpio.c"
#include "lcd.c"

#define GPIOB_BASE 0x40020400UL 
/*  Each Register has a base address for accessing its internal values. 
*   We define this address here to make it easier to understand the modular code.
*/
#define RCC_BASE 0x40023800UL //RCC Base register address
/*
*   RCC is the Reset Clock Configuration. The Base Address for RCC is where it starts.
*   RCC controls many different clocks, PLL configs, peripheral control, and more.
*/
#define RCC_CFGR (*(volatile uint32_t*)(RCC_BASE + 0x08)) //stores clock configuration of RCC
#define I2C_2_ADDRESS 0x40005800UL
volatile uint32_t device_addresses[128] = {0}; //Array to hold detected device addresses

#define I2C_ACKFAIL (1 << 10)
#define I2C_SB      (1 << 0)
#define I2C_TXE     (1 << 7)

int i2c_ping(uint8_t addr) {
    // Generate START
    I2C2->CR1 |= (1 << 8);
    while (!(I2C2->SR1 & (1 << 0)));

    // Send slave address with write bit (0)
    I2C2->DR = (addr << 1) | 0;

    // Small timeout loop for ACK
    for (volatile int i = 0; i < 10000; i++);

    if (I2C2->SR1 & I2C_ACKFAIL) {
        I2C2->SR1 &= ~I2C_ACKFAIL; // clear AF
        I2C2->CR1 |= (1 << 9);     // STOP
        return 0; // no device
    }

    while (!(I2C2->SR1 & I2C_TXE)); // wait until DR empty
    I2C2->CR1 |= (1 << 9);          // STOP
    return 1; // device exists
}


int main(void) {
    init_PB6and7_asI2C();
    // Optional: scan for devices
    lcd_init();
    lcd_write_string("Hello World!");

    while(1);
}

